apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo-app
spec:
  replicas: 3  # Number of replicas/pods
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-container
        image: julagantib/demo-api:v1.0  # Container image to use
        ports:
        - containerPort: 80  # Port to expose
